### PR TITLE
Add KColorChooser as supported tool

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution.

I initially chose to omit KColorChooser because there is apparently no command-line switch to go into "Pick Screen Color" mode directly. All the other tools just directly show a (crosshair) cursor to pick a color from the screen.

It might still be a good idea to provide KColorChooser as a fall-back (because I imagine there is a large group of users that have it pre-installed).

What do you think?

**Comment by data-man** [comment]
I'm KDE user, so I have no other color pickers. :)

**Comment by sharkdp** [comment]
Ok, thanks. It's probably better than having none at all :smile:

**Comment by sharkdp** [comment]
Released in [v0.6.0](https://github.com/sharkdp/pastel/releases).

**Comment by data-man** [comment]
@sharkdp 
Would be nice to allow the user to select a specific color choser if there are several of them installed.

**Comment by sharkdp** [comment]
Can you please open a new ticket for this request?

**Pull request merged**
